// <auto-generated />
using System;
using EDMS.Components.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EDMS.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260129023440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EDMS.Components.Models.Entity.ChatRoom", b =>
                {
                    b.Property<string>("IDX")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("IDX")
                        .HasComment("IDX 기본키");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Title")
                        .HasComment("채팅룸 제목");

                    b.Property<string>("UID")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("UID")
                        .HasComment("UID 고유값");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("UserId")
                        .HasComment("유저 ID");

                    b.HasKey("IDX")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "in_chat_UserId");

                    b.HasIndex(new[] { "UID" }, "in_chat_room_UID")
                        .IsUnique();

                    b.ToTable("chat_room", (string)null);
                });

            modelBuilder.Entity("EDMS.Components.Models.Entity.Chatting", b =>
                {
                    b.Property<string>("IDX")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("IDX")
                        .HasComment("IDX 기본키");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Content")
                        .HasComment("채팅 내용");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreateAt")
                        .HasComment("생성일");

                    b.Property<bool>("IsUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsUser")
                        .HasDefaultValueSql("'0'")
                        .HasComment("유저 구분자 0: 시스템, 1:유저");

                    b.Property<string>("Link_RoomId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("Link_RoomId")
                        .HasComment("연결된 채팅룸");

                    b.Property<string>("UID")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("UID")
                        .HasComment("UID 고유값");

                    b.HasKey("IDX")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Link_RoomId" }, "in_chatting_Link_RoomId");

                    b.ToTable("chatting", (string)null);
                });

            modelBuilder.Entity("EDMS.Components.Models.Entity.DocFileInfo", b =>
                {
                    b.Property<string>("IDX")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("IDX")
                        .HasComment("IDX 기본키");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreateAt")
                        .HasComment("생성일");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("FileName")
                        .HasComment("파일 이름");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FilePath")
                        .HasComment("저장 경로");

                    b.Property<int>("FileSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FileSize")
                        .HasDefaultValueSql("'0'")
                        .HasComment("파일 사이즈");

                    b.Property<string>("MainText")
                        .HasColumnType("text")
                        .HasColumnName("MainText")
                        .HasComment("간략 소개");

                    b.Property<string>("Registrant")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("Registrant")
                        .HasComment("등록자 UID");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("Tags")
                        .HasComment("태그");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Title")
                        .HasComment("파일 제목");

                    b.Property<string>("UID")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("UID")
                        .HasComment("UID 고유값");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdateAt")
                        .HasComment("수정일");

                    b.HasKey("IDX")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Title" }, "in_doc_file_info_Title");

                    b.HasIndex(new[] { "UID" }, "in_doc_file_info_UID")
                        .IsUnique();

                    b.ToTable("doc_file_info", (string)null);
                });

            modelBuilder.Entity("EDMS.Components.Models.Entity.DocFilePage", b =>
                {
                    b.Property<string>("IDX")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("IDX")
                        .HasComment("IDX 기본키");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("Content")
                        .HasComment("내용");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreateAt")
                        .HasComment("생성일");

                    b.Property<string>("Link_Doc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("Link_Doc")
                        .HasComment("연결된 문서");

                    b.Property<int>("PageNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PageNum")
                        .HasDefaultValueSql("'0'")
                        .HasComment("페이지 넘버");

                    b.Property<string>("UID")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("UID")
                        .HasComment("UID 고유값");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdateAt")
                        .HasComment("수정일");

                    b.HasKey("IDX")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Link_Doc" }, "in_doc_page_info_Link_Doc");

                    b.HasIndex(new[] { "UID" }, "in_doc_page_info_UID")
                        .IsUnique();

                    b.ToTable("doc_file_page", (string)null);
                });

            modelBuilder.Entity("EDMS.Components.Models.Entity.Chatting", b =>
                {
                    b.HasOne("EDMS.Components.Models.Entity.ChatRoom", "Link_RoomId_Navigation")
                        .WithMany("Chatting")
                        .HasForeignKey("Link_RoomId")
                        .HasPrincipalKey("UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chatting_Link_RoomId");

                    b.Navigation("Link_RoomId_Navigation");
                });

            modelBuilder.Entity("EDMS.Components.Models.Entity.DocFilePage", b =>
                {
                    b.HasOne("EDMS.Components.Models.Entity.DocFileInfo", "Link_Doc_Navigation")
                        .WithMany("DocFilePage")
                        .HasForeignKey("Link_Doc")
                        .HasPrincipalKey("UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doc_file_page_Link_Doc");

                    b.Navigation("Link_Doc_Navigation");
                });

            modelBuilder.Entity("EDMS.Components.Models.Entity.ChatRoom", b =>
                {
                    b.Navigation("Chatting");
                });

            modelBuilder.Entity("EDMS.Components.Models.Entity.DocFileInfo", b =>
                {
                    b.Navigation("DocFilePage");
                });
#pragma warning restore 612, 618
        }
    }
}
